import type { Locale } from "@/shared/lib/i18n";

const en = {
  task: "Task",
  plan: "Plan",
  evidence: "Evidence",
  result: "Result",
  progress: "Progress",
  currentStep: "Current step",
  noCurrentStep: "Preparing the next step",
  editPlan: "Edit plan",
  savePlan: "Save plan",
  cancel: "Cancel",
  start: "Start",
  pause: "Pause",
  resume: "Resume",
  retry: "Retry",
  stop: "Stop",
  queued: "Queued",
  pending: "Pending",
  planning: "Planning",
  running: "Running",
  waitingForApproval: "Waiting for approval",
  waitingForUser: "Waiting for your input",
  pauseRequested: "Pausing safely",
  paused: "Paused",
  cancelRequested: "Stopping safely",
  completed: "Completed",
  failed: "Needs attention",
  cancelled: "Stopped",
  ready: "Ready",
  draft: "Draft",
  skipped: "Skipped",
  stepFailed: "Failed",
  stepCancelled: "Cancelled",
  description: "Description",
  planTitle: "Plan title",
  planSummary: "Plan summary",
  stepTitle: "Step title",
  stepDescription: "What this step should accomplish",
  addStep: "Add step",
  removeStep: "Remove step",
  moveUp: "Move up",
  moveDown: "Move down",
  stepDetails: "Step details",
  attempts: "Attempts",
  noEvidence: "Evidence will appear as tools, citations, artifacts, and checkpoints are recorded.",
  noResult: "The final result will appear when the task completes.",
  checkpoint: "Checkpoint",
  source: "Open source",
  editHint: "Plan edits apply at the next safe boundary.",
  taskActivity: "Task activity",
  reconnecting: "Reconnecting",
  actionFailed: "Action failed",
} as const;

type TaskCopy = { [Key in keyof typeof en]: string };

const zh: TaskCopy = {
  task: "任务",
  plan: "计划",
  evidence: "证据",
  result: "结果",
  progress: "进度",
  currentStep: "当前步骤",
  noCurrentStep: "正在准备下一步",
  editPlan: "编辑计划",
  savePlan: "保存计划",
  cancel: "取消",
  start: "开始",
  pause: "暂停",
  resume: "继续",
  retry: "重试",
  stop: "停止",
  queued: "已排队",
  pending: "待执行",
  planning: "正在规划",
  running: "执行中",
  waitingForApproval: "等待审批",
  waitingForUser: "等待你补充信息",
  pauseRequested: "正在安全暂停",
  paused: "已暂停",
  cancelRequested: "正在安全停止",
  completed: "已完成",
  failed: "需要处理",
  cancelled: "已停止",
  ready: "已就绪",
  draft: "草稿",
  skipped: "已跳过",
  stepFailed: "失败",
  stepCancelled: "已取消",
  description: "说明",
  planTitle: "计划标题",
  planSummary: "计划摘要",
  stepTitle: "步骤标题",
  stepDescription: "描述这一步需要完成什么",
  addStep: "添加步骤",
  removeStep: "移除步骤",
  moveUp: "上移",
  moveDown: "下移",
  stepDetails: "步骤详情",
  attempts: "尝试次数",
  noEvidence: "工具、引用、成果和检查点产生后，会在这里形成可核验的证据。",
  noResult: "任务完成后，最终结果会显示在这里。",
  checkpoint: "检查点",
  source: "打开来源",
  editHint: "计划修改会在下一个安全边界生效。",
  taskActivity: "任务活动",
  reconnecting: "正在重新连接",
  actionFailed: "操作失败",
};

export function taskCopy(locale: Locale): TaskCopy {
  return locale === "zh" ? zh : en;
}
